### ISSUE TITLE
При выполнении алгоритма и выборе не продолжать, программа выдаёт ошибку

### ISSUE THREAD

**Issue by kontobaf** [DANIRU44/ultracryptographer#2]
![image](https://user-images.githubusercontent.com/43901953/177104280-def987f9-a261-4290-82fc-575d20238f9f.png)

**Comment by kontobaf** [comment]
Если нажать на клавишу Enter например, программа выдаёт краш

**Comment by DANIRU44** [comment]
исправлю в ближайшем патче
