### ISSUE TITLE
QR-код не создаётся

### ISSUE THREAD

**Issue by kontobaf** [DANIRU44/ultracryptographer#5]
Даже при вводе корректных значений в перестановочном шифре невозможно создать QR-код
![image](https://user-images.githubusercontent.com/43901953/177105883-a786988d-24b3-4dc9-8766-fc9903d36e4b.png)

**Comment by DANIRU44** [comment]
Здравствуйте, скорее всего у вас не установлен модуль qrcode, в связи с чем и возникает ошибка.

**Comment by kontobaf** [comment]
Модуль установлен, так как без него невозможно запустить программу
